[build]
  # Entra na pasta do projeto
  base = "MinhaVidaDashboard"
  
  # Comando de Build: Publica na pasta 'dist' (evitando o nome 'publish')
  command = "curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 10.0 --install-dir .dotnet && ./.dotnet/dotnet publish MinhaVidaDashboard.csproj -c Release -o dist"
  
  # Aponta para onde o index.html e _framework realmente estão
  publish = "dist/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false