[build]
  # Entra na pasta do projeto
  base = "MinhaVidaAPI"
  
  # Instala o SDK 10 e executa o publish usando o caminho completo do executável
  command = "curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 10.0 --install-dir .dotnet && ./.dotnet/dotnet publish -c Release -o publish"
  
  # O Netlify já estará dentro de 'MinhaVidaAPI' por causa do 'base' acima, 
  # então o publish deve ser relativo a essa pasta.
  publish = "publish/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200